name: On Push CI

on:
  push:
    branches:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
      env:
      REALM_TECHNICAL: ${{ secrets.REALM_TECHNICAL }}
      TOKEN_TECHNICAL: ${{ secrets.TOKEN_TECHNICAL }}
      SECRET_TECHNICAL: ${{ secrets.SECRET_TECHNICAL }}
    steps:
    - uses: actions/checkout@v3
    - name: Get all npm dependencies
      run : npm install
    - name: Unit Test (Jest)
      run : npm run test
    - name : install CLI
      run:  npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli
    - name: Validate Suiteapp
      run : npm run validate
